# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

users = User.create([
  { first_name: 'Олександр', last_name: 'Зіневич', email: 'zinevych@gmail.com', password: '12345678', password_confirmation: '12345678', date_of_birth: Time.now - 23.years, avatar: File.open(Rails.root + 'app/assets/images/test-users/avatar-zinevych-default.jpg'), phone: '+380881122333', location: 'Львів' },
  { first_name: 'Ігор', last_name: 'Павлик', email: 'padvlyk@gmail.com', password: '12345678', password_confirmation: '12345678', date_of_birth: Time.now - 23.years, avatar: File.open(Rails.root + 'app/assets/images/test-users/avatar-pavlyk-default.jpg'), phone: '+380882233444', location: 'Львів' },
  { first_name: 'Тарас', last_name: 'Шостак', email: 'shoctak@gmail.com', password: '12345678', password_confirmation: '12345678', date_of_birth: Time.now - 23.years, avatar: File.open(Rails.root + 'app/assets/images/test-users/avatar-shostak-default.jpg'), phone: '+380883344555', location: 'Львів' },
  { first_name: 'Юлія', last_name: 'Устимчук', email: 'ustymchuk@gmail.com', password: '12345678', password_confirmation: '12345678', date_of_birth: Time.now - 23.years, avatar: File.open(Rails.root + 'app/assets/images/test-users/avatar-ustymchuk-default.jpg'), phone: '+380883344666', location: 'Київ' },
  { first_name: 'Люда', last_name: 'Прокіпчук', email: 'prokipchuk@gmail.com', password: '12345678', password_confirmation: '12345678', date_of_birth: Time.now - 23.years, avatar: File.open(Rails.root + 'app/assets/images/test-users/avatar-prokipchuk-default.jpg'), phone: '+380883344777', location: 'Львів' }
])

pets = Pet.create([
  { name: 'Грім', gender: 'Він', age: 5, description: 'Міцно збита, компактна, мускулистий собака.Голова широка в черепній частині. Вуха невеликі, висячі, розташовані трохи позаду. Шия потужна, сильна.', avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-retriver.jpg'), user: users[0], kind: 'Пес', species: 'Лабрадор-ретривер' },
  { name: 'Зет', gender: 'Він', age: 3, description: 'Західноєвропейський тип німецької вівчарки відрізняється менш великими габаритами і короткими лапами. Для цієї породи характерна жорстка густа шерсть середньої довжини і забарвлення зонарно сірий, чорний і чорний з підпалинами, занурені рудий, сірий і сірий з підпалинами.', avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-vivcharka.jpg'), user: users[2], kind: 'Пес', species: 'Німецька вівчарка' },
  { name: 'Кетті', gender: 'Вона', age: 2, description: 'Дана порода котів має дике походження, а перші згадки про неї з’являються ще у Стародавньому Єгипті. Представники породи володіють атлетичним тілом та масивною головою. ', avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-chausi.jpg'), user: users[3], kind: 'Кіт', species: 'Чаузі' },
  { name: 'Ліка', gender: 'Вона', age: 4, description: 'Порода надзвичайно говірких домашніх котів з веселою вдачею і хижацьким окрасом короткої шерсті. Грайливі і цікаві коти серенгеті полюбляють прогулянки і товариство господарів.', avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-serengeti.jpg'), user: users[4], kind: 'Кіт', species: 'Серенгети' },
  { name: 'Аста', gender: 'Вона', age: 4, description: 'Кумедний кіт з великими круглими очима і невеликими вушками, що загинаються вперед до обличчя. Цей пухнастий представник спокійної домашньої породи стане чудовим вибором для більшості людей, що бажають завести сімейного улюбленця.', avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-scotland.jpg'), user: users[3], kind: 'Кіт', species: 'Шотландський кіт' },
  { name: 'Кара', gender: 'Вона', age: 4, description: "Корені цієї породи сягають XIX століття і пов'язані з ім'ям англійського аристократа лорда Твідмаута, який жив у Шотландії і присвячував своє дозвілля полюванню.", avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-gold-retriver.jpg'), user: users[2], kind: 'Пес', species: 'Золотистий ретрівер' },
  { name: 'Кася', gender: 'Вона', age: 4, description: "Історія виникнення і розвитку породи і цікава, і багато в чому показова, бо може служити прикладом того, наскільки сильно впливають на стан поголів'я витребеньки людини, підкріплені направленим добором.", avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-buldog.jpg'), user: users[2], kind: 'Пес', species: 'Англійський бульдог' },
  { name: 'Кнопка', gender: 'Вона', age: 4, description: "Йоркширський тер'єр - дивовижна порода собак, яка доброзичлива і дуже прівязчіва за характером. Крихітна з шовковистою шерстю, яка переливається золотим кольором, досить популярна в Америці і Європі.", avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-terier.jpg'), user: users[3], kind: 'Пес', species: "Йоркширський тер'єр" },
  { name: 'Рема', gender: 'Вона', age: 4, description: 'Собаки цієї породи відрізняються гарним характером, розумом і відданістю. Боксер дуже любить свого господаря і намагається ніколи не упускати його з поля зору. Ласкавий і поступливий.', avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-boxer.jpg'), user: users[2], kind: 'Пес', species: 'Боксер' },
  { name: 'Тера', gender: 'Вона', age: 4, description: 'Пудель втілює в собі давню мрію людства про рідкісний поєднанні привабливої зовнішності і завидного розуму. Правда, заворожено спостерігаючи за цими феєричними красенями всіх мастей – блондинами, брюнетами, шатен, володарями червоного, абрикосового, сріблястого забарвлень', avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-pudel.jpg'), user: users[0], kind: 'Пес', species: 'Пудель' },
  { name: 'Чіна', gender: 'Вона', age: 4, description: 'Ротвейлери — масивні, широкотілі, неквапливі собаки з великими головами. Забарвлення їхньої шерсті чорне з іржаво-червоними плямами на голові, на грудях і на лапах.', avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-rotveler.jpg'), user: users[0], kind: 'Пес', species: 'Ротвейлер' },
  { name: 'Юла', gender: 'Вона', age: 4, description: 'Однією з найпопулярніших порід в усьому світі вже довгі роки залишається такса. Характер цієї собаки дозволяє заводити її людям різного темпераменту і способу життя. Вона прекрасно підлаштовується під звички господаря. ', avatar: File.open(Rails.root + 'app/assets/images/test-pets/avatar-taksa.jpg'), user: users[1], kind: 'Пес', species: 'Такса' }
])

orders = Order.create([
  { start_date: Time.now + 2.days, end_date: Time.now + 7.days, user: users[0], pet: users[0].pets[0], title: 'Поcидіти з собакою', description: 'їду закордон,потрібна взяти собаку на тиждень' },
  { start_date: Time.now + 5.days, end_date: Time.now + 10.days, user: users[2], pet: users[2].pets[1], title: 'Поcидіти з котом', description: 'їду закордон,потрібна взяти кота на тиждень' },
  { start_date: Time.now + 5.days, end_date: Time.now + 10.days, user: users[2], pet: users[2].pets[1], title: 'Поcидіти з котом', description: 'їду закордон,потрібна взяти кота на тиждень' }
])

requests = Request.create([
  { message: 'Привіт. Я б хотів посидіти з Вашим улюбленцем протягом Вашої відпустки.', state: 'pending', user: users[1], order: orders[0] },
  { message: 'Доброго дня. У вас така гарна тваринка. Я б міг посидіти з нею.', state: 'pending', user: users[1], order: orders[1] }
])
